### ISSUE TITLE
ConcatenatedTransform.Inverse() method destroys the state of child transformations

### ISSUE THREAD

**Issue by Nipheris** [NetTopologySuite/ProjNet4GeoAPI#10]
The bug is related to [ConcatenatedTransform.Inverse()](https://github.com/NetTopologySuite/ProjNet4GeoAPI/blob/master/ProjNet/CoordinateSystems/Transformations/ConcatenatedTransform.cs#L129) method, which has unexpected side effects on child transformations in the list. Because of the absense of deep cloning of child transformations in [Clone()](https://github.com/NetTopologySuite/ProjNet4GeoAPI/blob/master/ProjNet/CoordinateSystems/Transformations/ConcatenatedTransform.cs#L149), the call of [Invert()](https://github.com/NetTopologySuite/ProjNet4GeoAPI/blob/master/ProjNet/CoordinateSystems/Transformations/ConcatenatedTransform.cs#L134) method on the cloned ConcatenatedTransform object leads to subsequent calls of Invert() on the original child transformations.

To fix this I suggest to reimplement ConcatenatedTransform.Inverse() method to make him create the new ConcatenatedTransform object from the subsequent calls of Inverse() on child transforms (not Invert()).

**Comment by FObermaier** [comment]
A unit test to prove your point and a patch file would be great.

**Comment by Nipheris** [comment]
Sure, I will fork the repo a bit later, and will provide fix and testcase.

**Comment by Nipheris** [comment]
Magnificent!! You fixed this! Thanks a lot!

Time to throw away our nasty workarounds :grinning:
