### ISSUE TITLE
Version 1.3.0.4 (NuGet) fails parsing any WKTs

### ISSUE THREAD

**Issue by Izhido** [NetTopologySuite/ProjNet4GeoAPI#15]
Version 1.3.0.4 of the library is plainly refusing to parse any WKT strings that are passed to `CoordinateSystemWKTReader.Parse()`, and thus, to `CoordinateSystemFactory.CreateFromWKT()`. 

EDIT: The issue was found in the PCL version of the library. Other versions were not tested.

A snapshot of the project's sources taken today (Jan 19, 2017), however, works just fine. The problem seems to be the specific .dlls published as part of the 1.3.0.4 NuGet.

The exception that is thrown when one attempts to parse a WKT is the following: 
(NOTE: 'P' corresponds to the first letter of whatever WKT string it's being sent to the function).

```
System.ArgumentException was unhandled by user code
  HResult=-2147024809
  Message='P' is not recognized.
  Source=ProjNET
  StackTrace:
       at ProjNet.Converters.WellKnownText.CoordinateSystemWktReader.Parse(String wkt)
       at ProjNet.CoordinateSystems.CoordinateSystemFactory.CreateFromWkt(String WKT)
       at <yada, yada, yada, >
  InnerException: 
```

**Comment by DGuidi** [comment]
have you tried with [1.3.2-pre1](https://www.nuget.org/packages/ProjNET4GeoAPI/1.3.2-pre1)?

**Comment by FObermaier** [comment]
This is no longer valid

**Comment by Izhido** [comment]
Confirmed. Whoever fixed the NuGet, thank you!
