### ISSUE TITLE
Help: Israeli Transverse Mercator

### ISSUE THREAD

**Issue by HarelM** [NetTopologySuite/ProjNet4GeoAPI#16]
Hi,

I'm trying to use the code in this library to implement a coordinate system transformation relevant to Israel.
The following wiki page describes it:
https://en.wikipedia.org/wiki/Israeli_Transverse_Mercator
I tried the following code but I can't get the required results:
Note: I wasn't sure what to put under ```central_meridian``` so I used the UTM zone number for Israel which is  36, and after calculations it returns 33.
```cs
        [TestMethod]
        public void TestItmFromJerusalem()
        {
            var coordinateTransformFactory = new CoordinateTransformationFactory();
            var coordinateSystemFactory = new CoordinateSystemFactory();
            var parameters = new List<ProjectionParameter>
            {
                new ProjectionParameter("latitude_of_origin", 31.734393611111109123611111111111),
                new ProjectionParameter("longitude_of_origin", 35.204516944444442572222222222222),
                new ProjectionParameter("central_meridian", 33),
                new ProjectionParameter("false_northing", 626907.390),
                new ProjectionParameter("false_easting", 219529.584),
                new ProjectionParameter("scale_factor", 1.0000067)
            };

            var itmGeo = coordinateSystemFactory.CreateGeographicCoordinateSystem("ITM", AngularUnit.Degrees, HorizontalDatum.ETRF89, // GRS80
                PrimeMeridian.Greenwich, new AxisInfo("East", AxisOrientationEnum.East), new AxisInfo("North", AxisOrientationEnum.North));

            var projection = coordinateSystemFactory.CreateProjection("Transverse_Mercator", "Transverse_Mercator", parameters);
            var itm = coordinateSystemFactory.CreateProjectedCoordinateSystem("ITM", itmGeo, projection, LinearUnit.Metre,
                new AxisInfo("East", AxisOrientationEnum.East), new AxisInfo("North", AxisOrientationEnum.North));

            string wkt = "GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137,298.257223563]],PRIMEM[\"Greenwich\",0],UNIT[\"Degree\",0.0174532925199433]]";
            var wgs84 = CoordinateSystemWktReader.Parse(wkt, Encoding.UTF8) as ICoordinateSystem;

            var jerusalem = new Coordinate(35.234383488170444, 31.776747919252124);

            var transfrom = coordinateTransformFactory.CreateFromCoordinateSystems(wgs84, itm);
            var transformed = transfrom.MathTransform.Transform(jerusalem);
            Assert.AreEqual(222286, transformed.X, 10);
            Assert.AreEqual(631556, transformed.Y, 10);
        }
```
Is the supplied data in the wiki incorrect? and I doning something wrong? I've been trying to figure this out for 2 days with no progress...

**Comment by FObermaier** [comment]
`Longitude_of_origin` and `Central_Meridian` are different names for the same value.

**Comment by HarelM** [comment]
Thanks for the quick response.
That might be true but neglecting to add the ```central_meridian``` parameter causes an exception...
Any other input regarding the issue I'm facing? I'm really stuck... :-/

**Comment by FObermaier** [comment]
In that case you have to provide the same value as for `longitude_of_origin`.

**Comment by HarelM** [comment]
Placing this value did not help solve the issue :-(

**Comment by FObermaier** [comment]
This WKT for your coordinate system gives deltas in mm range:
```
PROJCS["Israel / Israeli TM Grid",
    GEOGCS["Israel",
        DATUM["Israel",
            SPHEROID["GRS 1980",6378137,298.257222101,
                AUTHORITY["EPSG","7019"]],
            TOWGS84[-48,55,52,0,0,0,0],
            AUTHORITY["EPSG","6141"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.01745329251994328,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4141"]],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",31.73439361111111],
    PARAMETER["central_meridian",35.20451694444445],
    PARAMETER["scale_factor",1.0000067],
    PARAMETER["false_easting",219529.584],
    PARAMETER["false_northing",626907.39],
    AUTHORITY["EPSG","2039"],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH]]
```
It gives `(222285.99965981062, 631556.00379951776, NaN)` which is accurate to about 0.5 cm.

**Comment by HarelM** [comment]
Thanks!!! I'll give it a go tonight.
Is there a way to create it using code instead of this string?
Will ```Inverse()``` work? I tired it on another projection and got a not implemented exception.

**Comment by FObermaier** [comment]
>Is there a way to create it using code instead of this string?

yes, see [this example](https://github.com/NetTopologySuite/ProjNet4GeoAPI/blob/refactor/netStandard/ProjNet.Tests/GitHubIssues.cs#L74).
>Will `Inverse()` work? I tired it on another projection and got a not implemented exception.
No, it won't. Set up the opposite transformation by exchanging source and target coordinate systems.

**Comment by HarelM** [comment]
Is there a way to make the ```Inverse()``` work then? Should I create a small class that inherits from ```IMathTransform``` and implements the transform and inverse methods only (These are all the functions I need)?

**Comment by HarelM** [comment]
Question is answered and tested after #11 was implemented.
