### ISSUE TITLE
Convert latitude/longitude to Canada grid NAD83 (epsg:26910)

### ISSUE THREAD

**Issue by minhnguyenlinknode** [NetTopologySuite/ProjNet4GeoAPI#17]
I use the PCL version of this project to convert Canada coodinates between geo location (WGS84) and projected location NAD83 .

When I convert from NAD83 to WGS84, it works fine. But when I convert it back from WGS84 to NAD83 it is wrong.

My test case taken from http://epsg.io/26910: 

>  Latitude = 48.4185597
>  Longitude = -82.0479097
>  Easting    = 3523562.711189
>  Northing = 6246615.391161

My code to convert to projection is like this:

```
string target_WKT = "PROJCS[\"NAD83 / UTM zone 10N\",GEOGCS[\"NAD83\",DATUM[\"North_American_Datum_1983\",SPHEROID[\"GRS 1980\",6378137,298.257222101,AUTHORITY[\"EPSG\",\"7019\"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY[\"EPSG\",\"6269\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4269\"]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"latitude_of_origin\",0],PARAMETER[\"central_meridian\",-123],PARAMETER[\"scale_factor\",0.9996],PARAMETER[\"false_easting\",500000],PARAMETER[\"false_northing\",0],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH],AUTHORITY[\"EPSG\",\"26910\"]]"; 

var coordinateSystem_WGS = GeographicCoordinateSystem.WGS84;

var coordinateSystem_Target = CoordinateSystemWktReader.Parse(target_WKT) as IProjectedCoordinateSystem;

CoordinateTransformationFactory ctfac = new CoordinateTransformationFactory();
ICoordinateTransformation trans = ctfac.CreateFromCoordinateSystems(coordinateSystem_WGS, coordinateSystem_Target);

double[] fromPoint = new double[] { input.Longitude, input.Latitude };
double[] toPoint = trans.MathTransform.Transform(fromPoint);
```

I expect the toPoint return the easting and northing as above but not.
Note that when convert projection to lat/lon it is correct.

Any help?

**Comment by minhnguyenlinknode** [comment]
For more clear,  I am using the following WKT for Canada:

PROJCS["NAD83 / UTM zone 10N",
    GEOGCS["NAD83",
        DATUM["North_American_Datum_1983",
            SPHEROID["GRS 1980",6378137,298.257222101,
                AUTHORITY["EPSG","7019"]],
            TOWGS84[0,0,0,0,0,0,0],
            AUTHORITY["EPSG","6269"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4269"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",-123],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","26910"]]

Then when I convert from:
Easting = 3523562.711189
Northing = 6246615.391161

I got the following result which is correct:
Latitude = 48.4185597
Longitude = -82.0479097

Then when I do convert it back from:
Latitude = 48.4185597
Longitude = -82.0479097

Then I don't get the original Easting Northing as above, I get this one instead?
Eastings: 3476883.00068716 
Northings: 6227789.94450599

I think the problem from TransverseMercator.cs, between funtions RadiansToMetersJ() and MetersToRadians() ?

Could someone check it please?

**Comment by jajco84** [comment]
i think you are using wrong zone 
http://spatialreference.org/ref/epsg/26910/
WGS84 Bounds: -126.0000, 34.4000, -120.0000, 77.0000
your coordinates are so far away that RadiansToMeters returns nonsense
try using
http://spatialreference.org/ref/epsg/26917/
WGS84 Bounds: -84.0000, 24.0000, -78.0000, 83.0000

**Comment by minhnguyenlinknode** [comment]
Strange, WGS84 bounds is different from here http://epsg.io/26910
I will double check.

Thanks

**Comment by FObermaier** [comment]
@minhnguyenlinknode have you resolved your issue? All projection libraries that I could get a hold of compute values similar to those computed with ProjNet. (Proj4, DotSpatial.Projections)
