### ISSUE TITLE
WKT for proj4 string question

### ISSUE THREAD

**Issue by mludlum** [NetTopologySuite/ProjNet4GeoAPI#25]
I'm trying to convert an application that uses a proj4 library (C++) over to this library.  The app converts various projections to/from GPS coordinates assuming WGS84 for the GPS coordinates.  The code is using this proj4 init string:  **+proj=latlong +ellps=WGS84 +datum=NAD83**

I can't find an appropriate WKT string for this.  Upon researching, it seems that having WGS84 and NAD83 together isn't even valid.  Is that true?   I was planning on using GeographicCoordinateSystem.WGS84 to get the coordinate system, but my conversions are different by 2 degrees in the longitude and hundredth of degrees in latitude from the old code.

If there is an API that I missed that takes a proj4 string, please let me know.

Thanks.

**Comment by mknuepfer** [comment]
Same Problem here. How to create a coordinate system from an proj4string. 
CoordinateSystemFactory only contains method CreateFromWkt().

**Comment by airbreather** [comment]
[PROJ's own documentation](https://proj.org/development/reference/functions.html#c.proj_create) has this to say about proj-strings:

> The use of proj-string to describe a CRS is discouraged. It is a legacy means of conveying CRS descriptions: use of object codes (EPSG:XXXX typically) or WKT description is recommended for better expressivity.

So I'm not sure if it makes sense to implement new functionality to read this format.

-----

> I can't find an appropriate WKT string for this. Upon researching, it seems that having WGS84 and NAD83 together isn't even valid. Is that true? 

The NAD83 horizontal datum is defined on top of the GRS80 reference ellipsoid.

The WGS84 horizontal datum is defined on top of the WGS84 reference ellipsoid.

It's breaking my brain trying to think about what it means to say that you have coordinates in the NAD83 datum that use the WGS84 ellipsoid.

> I was planning on using GeographicCoordinateSystem.WGS84 to get the coordinate system, but my conversions are different by 2 degrees in the longitude and hundredth of degrees in latitude from the old code.

[EPSG:4269](http://epsg.io/4269) is probably going to be a better fit.
```
GEOGCS["NAD83",DATUM["North_American_Datum_1983",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","6269"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4269"]]
```

**Comment by mludlum** [comment]
airbreather, I sincerely appreciate the lesson on GRS80 vs WGS84 ellipsoids. That brought me a little closer to understanding this stuff.

**Comment by pchilds** [comment]
The difference between the GRS80 and WGS84 ellipsoid is only 0.1 mm (as such you may as well drop your +ellps=WGS84 as it won't make much of a difference even if it was possible). The only appreciable difference you get is when looking at the datums and where they place the centre and its orientation. ProjNET needs the TOWGS84 string to define these.

**Comment by mludlum** [comment]
I have since created a C# wrapper for the latest Proj 8 library and ditched ProjNET.  It takes WKTs and supports geoids.    Using SRID.csv from this repository to present CRS list to user.
