### ISSUE TITLE
Setting up proper build

### ISSUE THREAD

**Issue by xivk** [NetTopologySuite/ProjNet4GeoAPI#28]
I guess we need to setup a similar build system as we use in NTS/GeoAPI?

I have seen a start on the build server want me to finish up @FObermaier ?

**Comment by FObermaier** [comment]
@xivk, that would be great, thanks.

**Comment by xivk** [comment]
I don't understand why but the build is failing on support for .NET framework 3.5 (it's working for NTS), I'm going to postpone this, I've spent enough time on it for now... will get back to this sometime next week.

**Comment by xivk** [comment]
This could be relevant:

https://github.com/mj1856/TimeZoneConverter/commit/990bb739b266cbe217c458b8e394684d4bab532b

**Comment by FObermaier** [comment]
This seems to be complete.
