### ISSUE TITLE
Geocentric Coordinate System WKT Support

### ISSUE THREAD

**Issue by jhaverkost** [NetTopologySuite/ProjNet4GeoAPI#32]
The CoordinateSystemWktReader does not currently support GEOCCS WKT strings. Please add support for reading these strings.

I have already made the changes and manually built the library so I could use this right away. If acceptable, I will post a pull request once I get something integrated into the project's unit tests.

**Comment by FObermaier** [comment]
Sorry, c55aa4b13e9c3a1acfc8ca7a338159a0481ae03b had nothing to do with this.
