### ISSUE TITLE
Support of Hotine Oblique Mercator Azimuth Center projection

### ISSUE THREAD

**Issue by afroewis** [NetTopologySuite/ProjNet4GeoAPI#48]
Hi, 

For my use case, this coordinate system is very popular: https://epsg.io/2056 - it uses the Hotine Oblique Mercator Azimuth Center projection, which is currently not supported by this library. 

I am relatively new to geodesy, but I would like to improve my skills and therefore implement this projection. I am currently reading a book on geodesy that has a chapter about this projection and also contains the maths behind it. I also have access to a lot of reference points in LV95 (EPSG 2056). 

Before I work on this and create a PR, I would like to ask:

- Would this PR be appreciated, or is this projection not supported on purpose?
- Do you see any problems that hinders me in implementing this projection? 

Thank you!

Andreas

**Comment by airbreather** [comment]
What's missing from the existing [HotineObliqueMercatorProjection](https://github.com/NetTopologySuite/ProjNet4GeoAPI/blob/77e322a49c5543eae044b134f39ca44d46aab968/ProjNet/CoordinateSystems/Projections/HotineObliqueMercatorProjection.cs)?

The following code does give me a transformer, so I'm not sure if this is me being a bit naive, or if we just need to add "Hotine_Oblique_Mercator_Azimuth_Center" as an alias for "Hotine_Oblique_Mercator"...

```csharp
var csSrc = GeographicCoordinateSystem.WGS84;
var csTgt = new CoordinateSystemFactory().CreateFromWkt(@"PROJCS[""CH1903+ / LV95"",GEOGCS[""CH1903+"",DATUM[""CH1903+"",SPHEROID[""Bessel 1841"",6377397.155,299.1528128,AUTHORITY[""EPSG"",""7004""]],TOWGS84[674.374,15.056,405.346,0,0,0,0],AUTHORITY[""EPSG"",""6150""]],PRIMEM[""Greenwich"",0,AUTHORITY[""EPSG"",""8901""]],UNIT[""degree"",0.0174532925199433,AUTHORITY[""EPSG"",""9122""]],AUTHORITY[""EPSG"",""4150""]],PROJECTION[""Hotine_Oblique_Mercator""],PARAMETER[""latitude_of_center"",46.95240555555556],PARAMETER[""longitude_of_center"",7.439583333333333],PARAMETER[""azimuth"",90],PARAMETER[""rectified_grid_angle"",90],PARAMETER[""scale_factor"",1],PARAMETER[""false_easting"",2600000],PARAMETER[""false_northing"",1200000],UNIT[""metre"",1,AUTHORITY[""EPSG"",""9001""]],AXIS[""Y"",EAST],AXIS[""X"",NORTH],AUTHORITY[""EPSG"",""2056""]]");
var transformer = new CoordinateTransformationFactory().CreateFromCoordinateSystems(csSrc, csTgt);
```

The "naive" part is definitely possible, because I haven't worked with this code extensively...

**Comment by afroewis** [comment]
Hi @airbreather , thanks for the quick response. I will try this out and report back to you ASAP.

**Comment by afroewis** [comment]
Hi!

I did quite some research. I don't think that it's possible to just change the projection from `Hotine_Oblique_Mercator_Azimuth_Center` to `Hotine_Oblique_Mercator`.

Here are my findings:

This is the WGS84 lat/long of a point close to my office: 
Lat: 47.408735, Lon: 9.619803

If I convert this point to LV95 with EPSG (via https://epsg.io/transform#s_srs=4326&t_srs=2056&x=9.6198031&y=47.4087350), this is the result I get:
Y: 1253167.89,  X: 2764607.79
(I have a DXF that uses LV95 and I can confirm that this point is at the right location)

If I convert the above Lat/Long to the target CRS defined by the above WKT, the result is this point:
Y: 7581429.4812270831,
X: -1779335.9928703634

Honestly, I don't understand whether the Hotine_Oblique_Mercator_Azimuth_Center projection is completely different to Hotine_Oblique_Mercator, or if it's just Hotine_Oblique_Mercator with slightly different parameters. The name suggests the latter, but my understanding of projections is too limited to be able to judge. :(

However, I found this really helpful PDF published by the swiss tomography institute: https://www.swisstopo.admin.ch/de/home/meta/search.detail.document.html/swisstopo-internet/de/documents/geo-documents/swissprojectiongis.pdf.www.pdf.html

I quote from it:

> **Approximation of the Swiss Projection**
> In some GIS or calculation software the Swiss projection formulas are not implemented explicitly and
> the user has to define the Swiss projection and reference system manually. In this case, there exist
> several workarounds.
> For the oblique Mercator projection there exist several other formula sets than the ones introduced in
> Switzerland. The most known alternatives are the ones by Hotine (applied in Malaysia) and by Laborde (for Madagascar). The defining parameters may be different from the Swiss formula but the
> results are the same for all practical purposes.
> The original Hotine Oblique Mercator projection is implemented in most GIS. In order to use it in
> Switzerland, one can introduce all the official parameters of the Swiss projection except for the false
> easting. This has to be set to a value of -9'419'820.5907 m to obtain the same results as with the
> Swiss projection formulas. We do not recommend to use this option.
> A sub-version of the Hotine formulas is the Hotine Oblique Mercator (Azimuth Center). If this is
> available in your system, it is the best option to choose. All the official parameters of the Swiss projection can be used directly (including the false Easting). But there are 2 additional parameters to be defined: A scale factor which has to be set to 1.0 and the azimuth of the touching line in the projection
> centre, which has to be set to 90°. Exactly the same is valid if you can choose the Laborde projection.
> If in your system no formulas at all for an oblique Mercator projection are available, the best alternative
> is to use a Lambert Conformal Conic projection with 1 standard parallel. All the official Swiss parameters may be used, but the obtained differences with respect to the official oblique Mercator projection
> may reach up to 3 metres. 

I tried to use the LV95 CRS that's already included in ProjNet (in the CSV file) and changed the False Easting to `-9419820.5907`, but the results were very different to the actual value.

At this point I'm confused and I don't understand how the transformation with the Swiss coordinate systems work. The thing I would like to know if it's possible to write a workaround using the library (by changing some parameter), or if it's required to implement a new projection formula. In any case I'd be happy to contribute to this project, but I think I need a bit of help :(.

**Comment by afroewis** [comment]
I made some progress on this issue, I actually succeeded in calculating a WGS84 coordinate to a LV95 coordinate by applying an approximation formulas described in this PDF: https://www.swisstopo.admin.ch/content/swisstopo-internet/en/topics/survey/reference-systems/switzerland/_jcr_content/contentPar/tabs/items/dokumente_publikatio/tabPar/downloadlist/downloadItems/517_1459343190376.download/refsys_e.pdf

I hope I can find some time this weekend to work on this, maybe I manage to create a PR.

**Comment by terribletim** [comment]
Out of interest (and hopefully of some help) see this quote on [Hotine Oblique Mercator](http://desktop.arcgis.com/en/arcmap/10.3/guide-books/map-projections/hotine-oblique-mercator.htm#) **in relation to ESRI products**:
> Switzerland uses a different implementation of Oblique Mercator by Rosenmund, while Madagascar uses the Laborde version. These implementations are not compatible with the Oblique Mercator projection

[BlueMarble ](https://www.bluemarblegeo.com/knowledgebase/geocalc/classdef/projection/projections/hotineobliquemercator.html) describes the two variations of the projection (2 pts **vs** 1pt + azimuth) of which [https://epsg.io/2056](https://epsg.io/2056) is the latter. ### 1pt + azimuth appears to be the variant supported in [ProjNet](https://github.com/NetTopologySuite/ProjNet4GeoAPI/blob/develop/ProjNet/CoordinateSystems/Projections/HotineObliqueMercatorProjection.cs#L40)

From info you quote above:
>A sub-version of the Hotine formulas is the Hotine Oblique Mercator (Azimuth Center). If this is
available in your system, it is the best option to choose. All the official parameters of the Swiss projection can be used directly (including the false Easting). But there are 2 additional parameters to be defined: A scale factor which has to be set to 1.0 and the azimuth of the touching line in the projection
centre, which has to be set to 90°.

So without getting into details on the calcs, it seems that SRID 2056 _should_ be supported in ProjNet - the WKT projection is "Hotine_Oblique_Mercator" which is already being [registered](https://github.com/NetTopologySuite/ProjNet4GeoAPI/blob/develop/ProjNet/CoordinateSystems/Projections/ProjectionsRegistry.cs#L46). 
Maybe add a UnitTest to validate the Projection params, and another with a couple of test points?

**Comment by airbreather** [comment]
> Here are my findings:
> 
> This is the WGS84 lat/long of a point close to my office:
> Lat: 47.408735, Lon: 9.619803
> 
> If I convert this point to LV95 with EPSG (via https://epsg.io/transform#s_srs=4326&t_srs=2056&x=9.6198031&y=47.4087350), this is the result I get:
> Y: 1253167.89, X: 2764607.79
> (I have a DXF that uses LV95 and I can confirm that this point is at the right location)
> 
> If I convert the above Lat/Long to the target CRS defined by the above WKT, the result is this point:
> Y: 7581429.4812270831,
> X: -1779335.9928703634

Doing it myself, I get the right answer within a tenth of a meter.  It looks like you plugged in the longitude and latitude backwards... in ProjNet4GeoAPI, unusually, [longitude comes before latitude](https://github.com/NetTopologySuite/NetTopologySuite/issues/314#issue-442699331).

Here's the complete sample I used, to remove all doubt:

## ConsoleApp0.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ProjNet4GeoAPI" Version="1.4.1" />
  </ItemGroup>

</Project>
```

## Program.cs
```csharp
using System;

using ProjNet.CoordinateSystems;
using ProjNet.CoordinateSystems.Transformations;

class Program
{
    static void Main()
    {
        var csSrc = GeographicCoordinateSystem.WGS84;
        var csTgt = new CoordinateSystemFactory().CreateFromWkt(@"PROJCS[""CH1903+ / LV95"",GEOGCS[""CH1903+"",DATUM[""CH1903+"",SPHEROID[""Bessel 1841"",6377397.155,299.1528128,AUTHORITY[""EPSG"",""7004""]],TOWGS84[674.374,15.056,405.346,0,0,0,0],AUTHORITY[""EPSG"",""6150""]],PRIMEM[""Greenwich"",0,AUTHORITY[""EPSG"",""8901""]],UNIT[""degree"",0.0174532925199433,AUTHORITY[""EPSG"",""9122""]],AUTHORITY[""EPSG"",""4150""]],PROJECTION[""Hotine_Oblique_Mercator""],PARAMETER[""latitude_of_center"",46.95240555555556],PARAMETER[""longitude_of_center"",7.439583333333333],PARAMETER[""azimuth"",90],PARAMETER[""rectified_grid_angle"",90],PARAMETER[""scale_factor"",1],PARAMETER[""false_easting"",2600000],PARAMETER[""false_northing"",1200000],UNIT[""metre"",1,AUTHORITY[""EPSG"",""9001""]],AXIS[""Y"",EAST],AXIS[""X"",NORTH],AUTHORITY[""EPSG"",""2056""]]");
        var transformer = new CoordinateTransformationFactory().CreateFromCoordinateSystems(csSrc, csTgt);

        double[] longitudeAndLatitude = { 9.619803, 47.408735 };
        double[] xy = transformer.MathTransform.Transform(longitudeAndLatitude);

        Console.WriteLine($"X: {xy[0]:F2}"); // writes "X: 2764607.70"
        Console.WriteLine($"Y: {xy[1]:F2}"); // writes "Y: 1253167.89"
    }
}
```

**Comment by afroewis** [comment]
That's embarrassing 😢 . Thanks for your help, @airbreather 

Anyway, I think it does make sense to add an alias for the "Azimuth Center" string. I will submit a PR for it.

**Comment by airbreather** [comment]
> Anyway, I think it does make sense to add an alias for the "Azimuth Center" string. I will submit a PR for it.

Already done: e93ab00

**Comment by afroewis** [comment]
Perfect, thanks a lot. 

I will close this issue now.
