### ISSUE TITLE
About the 'Gauss_Kruger' projection and 'Bursa' transformation

### ISSUE THREAD

**Issue by mumumi** [NetTopologySuite/ProjNet4GeoAPI#53]
I tried to transform coordinations in 'Gauss_Kruger' projection by replacing it with 'Transverse_Mercator'. The deviation of result is too large. Bursa model with seven parameters is usually used in my daily work to tranform coordinations in 'Gauss_Kruger' projection. Pardon me for my ignorance. What's the different to implement 'BursaTransform.cs'? Is there a plan to implement it?

**Comment by terribletim** [comment]
Short answer is that ProjNet supports 7 parameter datum transformation commonly known as Bursa-Wolf.

Long answer is there seems to be some confusion. Briefly, a Projected Coordinate System (PCS) is an algorithm (Projection) that has an underlying Geographic Coordinate System (GCS) which in turn is based upon a Datum (this is where you'll see the Ellipsoid).

To switch Projected Coordinate System, you typically go via the Geographic Coordinate System. **And** if the Geographic Coordinate System of PCS A and PCS B are not the same, you need a datum transformation to move between GCS A and GCS B. Transformation parameters are widely published from most Geographic Coordinate Systems to WGS84, so in most cases the datum transformation sequence will go via WGS84.

So depending on your use case, you could be looking at one of the following:

- PCS A >> common GCS >> PCS B (basic re-project)
- PCS A >> GCS A >> GCS B >> PCS B (assuming GCS A or B is WGS84)
- PCS A >> GCS A >> WGS84 >> GCS B >> PCS B

And always use a published test point or independent (online) calculation to verify your transformation.

There are several thorough explanations on the web, such as http://desktop.arcgis.com/en/arcmap/10.3/guide-books/map-projections/about-geographic-coordinate-systems.htm, and for PCS, GCS, and transformation parameters see [EPSG](https://epsg.io/)

**Comment by mumumi** [comment]
> Short answer is that ProjNet supports 7 parameter datum transformation commonly known as Bursa-Wolf.
> 
> Long answer is there seems to be some confusion. Briefly, a Projected Coordinate System (PCS) is an algorithm (Projection) that has an underlying Geographic Coordinate System (GCS) which in turn is based upon a Datum (this is where you'll see the Ellipsoid).
> 
> To switch Projected Coordinate System, you typically go via the Geographic Coordinate System. **And** if the Geographic Coordinate System of PCS A and PCS B are not the same, you need a datum transformation to move between GCS A and GCS B. Transformation parameters are widely published from most Geographic Coordinate Systems to WGS84, so in most cases the datum transformation sequence will go via WGS84.
> 
> So depending on your use case, you could be looking at one of the following:
> 
> * PCS A >> common GCS >> PCS B (basic re-project)
> * PCS A >> GCS A >> GCS B >> PCS B (assuming GCS A or B is WGS84)
> * PCS A >> GCS A >> WGS84 >> GCS B >> PCS B
> 
> And always use a published test point or independent (online) calculation to verify your transformation.
> 
> There are several thorough explanations on the web, such as http://desktop.arcgis.com/en/arcmap/10.3/guide-books/map-projections/about-geographic-coordinate-systems.htm, and for PCS, GCS, and transformation parameters see [EPSG](https://epsg.io/)

Thank you very much for your patient and professional explanation.
