### ISSUE TITLE
Disable CS1591 "Missing XML comment for publicly visible type or member"

### ISSUE THREAD

**Issue by r-pankevicius** [NetTopologySuite/ProjNet4GeoAPI#57]
Example:
CoordinateSystemServices.cs(308,24,308,43): warning CS1591: Missing XML comment for publicly visible type or member 'CoordinateSystemServices.AddCoordinateSystem(int, CoordinateSystem)'

**Comment by airbreather** [comment]
I've left it enabled because IMO we should be fixing those instead of disabling the rule, especially now that we use DocFX to use it to generate a documentation website for NetTopologySuite and we may follow suit for this as well.

**Comment by r-pankevicius** [comment]
Well, I have a real life experience how guys working "according to standards" just left these comments empty. So I don't believe in any use of it except people trying to get rid of this issue at max speed. And it is very easy in Visual studio: type /// before the method and you'll get generated empty comments complying to the rule.

I accept everything that works and promptly reject anything that doesn't.

**Comment by r-pankevicius** [comment]
OK, I will close it. Maybe if you will use comments to generate a documentation, it's better to have this warning on.
