### ISSUE TITLE
Support .NET Core 3.0

### ISSUE THREAD

**Issue by yjacques940** [NetTopologySuite/ProjNet4GeoAPI#59]
We recently upgraded to dotnet core 3.0. We need GeoAPI in our api. We actually need this feature as fast as possible, to deploy in production. 

What's needed : 
- Make the GeoAPI compatible with .net core 3.0

Please answer me when i'ts done.
Thanks

**Comment by airbreather** [comment]
Please see my response from the other issue: https://github.com/NetTopologySuite/GeoAPI/issues/71#issuecomment-555014067
