### ISSUE TITLE
Valid WKTs for SRIDs 4326 and 3857?

### ISSUE THREAD

**Issue by Rumpelstinsk** [NetTopologySuite/ProjNet4GeoAPI#62]
I get WKT from https://epsg.io/4326 and https://epsg.io/3857

However that codes throw me an exception when I try to use them:

```
private void changeSRID(Geometry item, out double lat, out double lng)
        {
            //From coordinate sytem 4326
            var wkt4326 = "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\", 6378137, 298.257223563,AUTHORITY[\"EPSG\", \"7030\"]],AUTHORITY[\"EPSG\", \"6326\"]],PRIMEM[\"Greenwich\", 0,AUTHORITY[\"EPSG\", \"8901\"]],UNIT[\"degree\", 0.0174532925199433,AUTHORITY[\"EPSG\", \"9122\"]],AUTHORITY[\"EPSG\", \"4326\"]]";
            GeoAPI.CoordinateSystems.IGeographicCoordinateSystem fromCS =
                ProjNet.Converters.WellKnownText.CoordinateSystemWktReader.Parse(wkt4326, Encoding.UTF8) as GeoAPI.CoordinateSystems.IGeographicCoordinateSystem;

            //To Corordinate system 3857
            var wkt3857 = "PROJCS[\"WGS 84 / Pseudo-Mercator\",GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]],PROJECTION[\"Mercator_1SP\"],PARAMETER[\"central_meridian\",0],PARAMETER[\"scale_factor\",1],PARAMETER[\"false_easting\",0],PARAMETER[\"false_northing\",0],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"X\",EAST],AXIS[\"Y\",NORTH],EXTENSION[\"PROJ4\",\"+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs\"],AUTHORITY[\"EPSG\",\"3857\"]]";
            GeoAPI.CoordinateSystems.IProjectedCoordinateSystem toCS =
                ProjNet.Converters.WellKnownText.CoordinateSystemWktReader.Parse(wkt3857, Encoding.UTF8) as GeoAPI.CoordinateSystems.IProjectedCoordinateSystem;
                       
            //Transformation
            CoordinateTransformationFactory ctfac = new CoordinateTransformationFactory();
            ICoordinateTransformation trans = ctfac.CreateFromCoordinateSystems(fromCS, toCS);

            double[] fromPoint = new double[] { item.Coordinates[0].X, item.Coordinates[0].Y };
            double[] toPoint = trans.MathTransform.Transform(fromPoint);
            lat = toPoint[0];
            lng = toPoint[1];
        }
```

I take a look to SRID.csv file of your project, but i couldn't find any ID with 3857. 
So, Where can I find the correct WKT for both SRIDs?

**Comment by FObermaier** [comment]
You should use
```C#
// Coordinate systems
var cs4386 = ProjNet.CoordinateSystems.GeographicCoordinateSystem.WGS84;
var cs3857 = ProjNet.CoordinateSystems.ProjectedCoordinateSystem.WebMercator;

// Transformation
var ctfac = new CoordinateTransformationFactory();
var trans = ctfac.CreateFromCoordinateSystems(cs4326, cs3857);

```

**Comment by Rumpelstinsk** [comment]
With that code I don't get the same result as Postgis.

For example, I have this Poin in 3857t:
`POINT (-8227435.375733535 4993567.966062075)`

If I execute this query in postgis:

```
select 
	st_x(st_transform(ST_SetSRID(ST_Point(-8227435.375733535, 4993567.966062075), 3857), 4326)) AS lng,
	st_y(st_transform(ST_SetSRID(ST_Point(-8227435.375733535, 4993567.966062075), 3857), 4326)) AS lat
```

I get this result (which is the expected result)

> Lng(x) = -73.90830947127071
> Lat(y) =40.872597628718

However, with your code, i get this result;

> Lng(x) = -915873916561.22253
> Lat(y) = 889648.8290110504

**Comment by Rumpelstinsk** [comment]
Thanks for the help. That did the trick

**Comment by Bernoulli-IT** [comment]
Yes this helped. But why don't the WKT definitions, as mentioned by OP, lead to the correct results? That is odd and feels uncomfortable.

**Comment by DGuidi** [comment]
@Bernoulli-IT I tried to run code posted by @Rumpelstinsk and no exception is thrown

**Comment by Bernoulli-IT** [comment]
> 
> 
> @Bernoulli-IT tried to run code posted by @Rumpelstinsk and no exception is thrown

I think I misplaced my previous comment as I bumped into a similar issue where a conversion resulted in an incorrect y value. My bad.

**Comment by airbreather** [comment]
> Yes this helped. But why don't the WKT definitions, as mentioned by OP, lead to the correct results? That is odd and feels uncomfortable.

This is a valid question.  From https://github.com/NetTopologySuite/ProjNet4GeoAPI/issues/37#issuecomment-470947156:
> The issue is that the projection "Mercator_1SP" needs additional help to perform the correct conversion.
> Out of the box, proj4 wouldn't compute the correct result either, that is why the Extension token is there.
>
> Add `[PARAMETER["semi_minor",6378137]]` anywhere in the parameter block and you should be all set.
> Or use `ProjectedCoordinateSystem.WebMercator` in the first place.
