### ISSUE TITLE
Projection.WKT should output ClassName, not Name

### ISSUE THREAD

**Issue by jarobbins** [NetTopologySuite/ProjNet4GeoAPI#68]
If I create a UTM 17N projection and view its WKT, I see the following for its projection parameter:  PROJECTION["UTM17N", AUTHORITY["EPSG", "32617"]].

That should be:  PROJECTION["Transverse_Mercator", AUTHORITY["EPSG", "32617"]].

I noticed this because I serialize many coordinate systems as WKT, then parse them later to do transformations, etc.  Attempting to create a transformation when one of the projection classes is "UTM17N" causes a Not Supported exception in ProjectionsRegistry.

The following test will fail:

```csharp
var utm17n_original = ProjNet.CoordinateSystems.ProjectedCoordinateSystem.WGS84_UTM(17, true);
string utm17n_wkt = utm17n_original.WKT;
var utm17n_fromWKT = (ProjNet.CoordinateSystems.ProjectedCoordinateSystem)ProjNet.IO.CoordinateSystems.CoordinateSystemWktReader.Parse(utm17n_wkt);

var wgs84 = ProjNet.CoordinateSystems.GeographicCoordinateSystem.WGS84;

var coordinateSystemServices = new ProjNet.CoordinateSystemServices();
Assert.DoesNotThrow(() => coordinateSystemServices.CreateTransformation(utm17n_fromWKT, wgs84));
```

I'm creating a pull request with the fix and the above test case.

**Comment by ghost** [comment]
In the latest 2.0.0 here is how I can reproduce this error:

I use the following shim to export parseable UTM WKT:

```c#
public class Location {
  public double Latitude { get; set; }
  public double Longitude { get; set; }
}

public static ProjectedCoordinateSystem UtmProjection(this Location location) => ProjectedCoordinateSystem
  .WGS84_UTM((int)MapProjection.CalcUtmZone(location.Longitude), location.Latitude > 0);

// TODO: No reference to 'Transverse_Mercator' exists so add it
public static string UtmWkt(this Location location) => Regex.Replace(
  location.UtmProjection().WKT, 
  @"PROJECTION\[""UTM\w+""",
  @"PROJECTION[""Transverse_Mercator"""
);
```

I'm not sure why it's missing and I ran out of time investigating, but here is a test case to reproduce the issue:

```c#
var projectionFile = "...file";
File.WriteAllText(projectionFile, new Location(40.7128, 74.0060).UtmWkt());

CoordinateSystemWktReader.Parse(File.ReadAllText(projectionFile));
```

Without the regex replace I get:
> System.NotSupportedException: Projection UTM43N is not supported.
System.NotSupportedException
Projection UTM43N is not supported.
   at ProjNet.CoordinateSystems.Projections.ProjectionsRegistry.CreateProjection(String className, IEnumerable`1 parameters) at
ProjNet.CoordinateSystems.Transformations.CoordinateTransformationFactory.CreateCoordinateOperation(IProjection projection, Ellipsoid ellipsoid, LinearUnit unit) at ProjNet.CoordinateSystems.Transformations.CoordinateTransformationFactory.Proj2Geog(ProjectedCoordinateSystem source, GeographicCoordinateSystem target) at ProjNet.CoordinateSystems.Transformations.CoordinateTransformationFactory.CreateFromCoordinateSystems(CoordinateSystem sourceCS, CoordinateSystem targetCS)
