### ISSUE TITLE
WktStreamTokenizer fails to parse numeric value with exponent notation

### ISSUE THREAD

**Issue by vicocz** [NetTopologySuite/ProjNet4GeoAPI#7]
WktStreamTokenizer fails to parse numeric value with exponent notation. Such value might be supported. See chapter 6.3.2 in in WKT decription document at http://docs.opengeospatial.org/is/12-063r5/12-063r5.html

WKT example: PARAM_MT["Affine",PARAMETER["num_row", 3],PARAMETER["num_col", 3],PARAMETER["elt_0_0", 6.12303176911189E-17]]

**Comment by FObermaier** [comment]
Can this be closed?

**Comment by FObermaier** [comment]
@vicocz Can this be closed?

**Comment by vicocz** [comment]
Yes, unit tests seem to work.
