### ISSUE TITLE
Most Projections used in ProjectionsRegistry are declared "internal"

### ISSUE THREAD

**Issue by jarobbins** [NetTopologySuite/ProjNet4GeoAPI#71]
In the process of porting a code base from DotSpatial to ProjNet/NTS, I found that not every projection type I needed is supported out of the box.  In particular, I have some prj files from different sources that specify "Gauss-Kruger" projection.  DotSpatial treats this as a synonym for "Transverse Mercator", so I thought I would just register an additional projection in the registry.

This would do the trick:
> ProjNet.CoordinateSystems.Projections.ProjectionsRegistry.Register("gauss_kruger", typeof(ProjNet.CoordinateSystems.Projections.TransverseMercator));

But, `TransverseMercator` is not accessible to me (without some reflection).  Is there any reason to not make those MapProjection-derived classes public?  If not, I have a pull request coming at you.

**Comment by FObermaier** [comment]
I don't like to do this. If anyone wants to add new projection classes, it can be done by submitting to this project.

**Comment by airbreather** [comment]
Implementation details should not be `public` unless there's a specific reason to make them that way... and `MapProjection`-derived types sure look like implementation details to me.

For problems like this one where you have a problem that you need to solve without waiting for us to provide a specific alias, I'd much rather expose something like:

```csharp
ProjectionsRegistry.Register("gauss_kruger", "transverse_mercator");
```

**Comment by jarobbins** [comment]
@airbreather Maybe this would make it more obvious:

`ProjectionsRegistry.RegisterAlias("gauss_kruger", "transverse_mercator");`

Also, `LambertAzimuthalEqualAreaProjection` was public, so I'm guessing that's an oversight.  I can modify #72 to change the MapProjection classes back to internal, and I'll take a crack at the RegisterAlias method.

**Comment by FObermaier** [comment]
I think the `RegisterAlias` is good. There can be aliasses not only for coordinate transformation methods. We should consider providing/registering aliases for other items as well, sth. along the lines what proj is doing ([see this](https://github.com/NetTopologySuite/ProjNet4GeoAPI/files/4632605/proj_db_alias.zip))

**Comment by jarobbins** [comment]
@FObermaier I can tackle that. It'll take a bit of time, since I'll need to get familiar with more of the ProjNet code base.  Should those additional changes be done on a different issue/pull request? Or keep it all with this one?

**Comment by FObermaier** [comment]
I think it deserves a fresh start. There is currently no alias resolving mechanism in ProjNet besides the hard coded one on coordinate transformation method
