### ISSUE TITLE
Typo in code sample on Wiki

### ISSUE THREAD

**Issue by philipbelesky** [NetTopologySuite/ProjNet4GeoAPI#88]
In `Constructing-a-Coordinate-System-by-code.md` the first code sample begins with:

`GepAPI.CoordinateSystem.ICoordinateSystemFactory cFac`

I think that should instead be:

`GeoAPI.CoordinateSystems.ICoordinateSystemFactory cFac`

Changes are "Gep" > "Geo" and "CoordinateSystem" into "CoordinateSystems". Sorry for the lack of PR - I couldn't immediately figure out how to PR against a wiki.

**Comment by airbreather** [comment]
Fixed, thanks
